# .github/workflows/ci.yml

name: Python Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint-and-scan: # Можно переименовать job для ясности
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Нужно для SonarCloud, чтобы он мог получить историю коммитов
        with:
          fetch-depth: 0 # Важно для анализа истории

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Убедись, что версия совпадает

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: make install

      - name: Run linter
        run: make lint

      # === НОВЫЙ ШАГ ===
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # === КОНЕЦ НОВОГО ШАГА ===